### ISSUE TITLE
Module 'commot' has no attribute 'pp'

### ISSUE THREAD

**Issue by sykesmarc** [zcang/COMMOT#22]
Hello, 

I am writing to you because I am currently using your module, but I have been finding this issue specially in this line, which has not let me go further in the analysis I am conducting. 

```
>>> df_cellchat = ct.pp.ligand_receptor_database(species='mouse', signaling_type='Secreted Signaling', database='CellChat')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'commot' has no attribute 'pp'
```

I have checked everything and I don't seem to find the reason of the problem. I am currently working on Python 3.8.10, and I have installed the last version of COMMOT through GitHub. 

When I import the module I get this warning, which I don't know If it has something to do.

```
>>> import commot as ct
/commot/lib/python3.8/site-packages/anndata/_core/anndata.py:1840: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/commot/lib/python3.8/site-packages/anndata/_core/anndata.py:1840: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
```

It would mean a lot if you could help me,
Thanks for everything.

Marc
